openapi: 3.0.0
info:
  version: "2.16.0"
  title: GovPay - API Pagamento
  description: 'GovPay - API Pagamento V2 - Avvio pagamento tramite Checkout PagoPA'
  contact:
    name: GitHub Project Page
    url: 'https://github.com/link-it/GovPay/'
  license:
    name: GPL
    url: 'https://github.com/link-it/GovPay/blob/master/LICENSE'
servers:
  - url: /govpay-pagamenti-api/rs/basic/v2/
tags:
  - name: Pagamenti
    description: Avvio del pagamento delle pendenze tramite Checkout PagoPA
security:
  - basicAuth: []
paths:
  '/pagamenti':
    post:
      operationId: addPagamento
      summary: Avvio di un pagamento di pendenze
      tags:
        - Pagamenti
      description: >-
        L'operazione consente di avviare una sessione di pagamento per una o più
        pendenze. Le pendenze presenti in posizione debitoria possono essere
        riferite tramite identificativo della pendenza del gestionale proprietario
        (_idA2A_ e _idPendenza_) oppure con gli estremi dell'avviso (_idDominio_
        e _iuv_). Nel caso invece di pendenze spontanee, è possibile
        fornire direttamente i dati costitutivi.
      parameters:
        - $ref: '#/components/parameters/idSessionePortale'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NuovoPagamento'
      responses:
        '201':
          description: Pagamento creato
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagamentoCreato'
        '302':
          description: Pagamento inoltrato al Checkout PagoPA. L'header Location contiene la URL verso cui reindirizzare l'utente.
          headers:
            Location:
              description: URL del Checkout PagoPA
              schema:
                type: string
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401NotAuthenticated'
        '403':
          $ref: '#/components/responses/403NotAuthorized'
        '503':
          $ref: '#/components/responses/500ServiceUnavailable'
        '502':
          $ref: '#/components/responses/502BadGateway'

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  parameters:
    idSessionePortale:
      name: idSessionePortale
      in: query
      description: Identificativo della sessione di pagamento assegnato dall'EC
      required: false
      schema:
        type: string
      example: 'c8be909b-2feb-4ffa-8f98-704462abbd1d'
  responses:
    '400BadRequest':
      description: Richiesta non correttamente formata
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/FaultBean'
          example:
            categoria: RICHIESTA
            codice: '00001'
            descrizione: Messaggio di richiesta non valido
            dettaglio: Codice Avviso non conforme alle specifiche pagoPA
    '401NotAuthenticated':
      description: Richiesta non autenticata
    '403NotAuthorized':
      description: Richiesta non autorizzata
    '500ServiceUnavailable':
      description: Servizio non disponibile
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/FaultBean'
          example:
            categoria: INTERNO
            codice: INTERNO
            descrizione: Servizio non disponibile
    '502BadGateway':
      description: Rilevato errore con la piattaforma PagoPA
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/FaultBeanEsteso'
          example:
            categoria: PAGOPA
            codice: PPT_CANALE_IRRAGGIUNGIBILE
            descrizione: Errore di connessione verso il canale     
            id: '12345'
            location: '/pagamenti/12345'     
  schemas:
    Bollo:
      description: Definisce i dati di un bollo telematico
      type: object
      required:
        - tipoBollo
        - hashDocumento
        - provinciaResidenza
      properties:
        tipoBollo:
          description: Tipologia di Bollo digitale
          type: string
          enum:
            - Imposta di bollo
        hashDocumento:
          description: Digest in base64 del documento informatico associato alla marca da bollo
          type: string
          example: "--- base64 ---"
          maxLength: 70
        provinciaResidenza:
          description: Sigla automobilistica della provincia di residenza del soggetto pagatore
          type: string
          example: "RO"
          pattern: "[A-Z]{2,2}"
    Contabilita:
      type: object
      properties:
        quote:
          type: array
          items: 
            $ref: '#/components/schemas/QuotaContabilita'
        proprietaCustom:
          type: object
          description: Dati specifici del gestionale di contabilità
    Conto:
      type: object
      required:
        - iban
      properties:
        iban:
          type: string
          example: IT60X0542811101000000123456
          pattern: "[a-zA-Z]{2,2}[0-9]{2,2}[a-zA-Z0-9]{1,30}"
        bic:
          type: string
          example: DABAIE2D
          pattern: "[A-Z]{6,6}[A-Z2-9][A-NP-Z0-9]([A-Z0-9]{3,3}){0,1}"
    Entrata:
      description: Definisce i dettagli di una entrata.
      type: object
      required:
        - ibanAccredito
        - tipoContabilita
        - codiceContabilita
      properties:
        ibanAccredito:
          type: string
          example: IT60X0542811101000000123456
          pattern: "[a-zA-Z]{2,2}[0-9]{2,2}[a-zA-Z0-9]{1,30}"
        ibanAppoggio:
          type: string
          example: IT60X0542811101000000123456
          pattern: "[a-zA-Z]{2,2}[0-9]{2,2}[a-zA-Z0-9]{1,30}"
        tipoContabilita:
          $ref: '#/components/schemas/TipoContabilita'
        codiceContabilita:
          description: Codifica del capitolo di bilancio
          type: string
          example: '3321'
          minLength: 1
          maxLength: 135
    FaultBean:
      type: object
      required:
        - categoria
        - codice
        - descrizione
      properties:
        categoria:
          type: string
          description: >-
            Categoria dell'errore riscontrato:
             * `AUTORIZZAZIONE` - Operazione non autorizzata
             * `RICHIESTA` - Richiesta non valida
             * `OPERAZIONE` - Operazione non eseguibile
             * `PAGOPA` - Errore da PagoPA
             * `EC` - Errore da Ente Creditore
             * `INTERNO` - Errore interno
          enum:
            - AUTORIZZAZIONE
            - RICHIESTA
            - OPERAZIONE
            - PAGOPA
            - EC
            - INTERNO
        codice:
          type: string
          description: Codice di errore
        descrizione:
          type: string
          description: Descrizione dell'errore
        dettaglio:
          type: string
          description: Descrizione aggiuntiva 
    FaultBeanEsteso:
      type: object
      allOf:
        - $ref: '#/components/schemas/FaultBean'
        - type: object
          properties:
            id:
              type: string
              example: '12345'
              description: identificativo del pagamento creato
            location:
              type: string
              example: /pagamenti/12345
              description: Url del dettaglio del pagamento   
    LinguaPagamento:
      description: Indica la lingua da utilizzare durante il pagamento sul Checkout
      example: 'it'
      type: string
      enum:
        - 'it'
        - 'en'
        - 'fr'
        - 'sl'
        - 'de'
    LinguaSecondaria:
      example: 'false'
      type: string
      enum:
        - 'false'
        - 'de'
        - 'en'
        - 'fr'
        - 'sl'
    MapEntry:
      type: object
      required:
        - key
        - value
      properties:
        key:
          type: string
          description: chiave del metadata
          minLength: 1
          maxLength: 140
        value:
          type: string
          description: valore del metadata
          minLength: 1
          maxLength: 140
    Metadata:
      type: object
      description: Metadata Custom da inserire nella ricevuta di pagamento
      properties:
        mapEntries:
          type: array
          items: 
            $ref: '#/components/schemas/MapEntry'      
          minItems: 1
          maxItems: 5
    NuovaPendenza:
      type: object
      allOf:
        - $ref: "#/components/schemas/RiferimentoPendenza"
        - type: object
          required:
            - idTipoPendenza
            - idDominio
            - causale
            - soggettoPagatore
            - importo
            - voci
          properties:
            idDominio:
              type: string
              description: Identificativo del dominio creditore
              example: '12345678901'
              minLength: 1
              maxLength: 35
              pattern: '(^([0-9]){11}$)'
            idUnitaOperativa:
              type: string
              description: Identificativo dell'unita' operativa
              example: UO33132
              minLength: 1
              maxLength: 35
              pattern: '(^[a-zA-Z0-9\-_]{1,35}$)'
            idTipoPendenza:
              type: string
              description: Identificativo della tipologia pendenza
              example: IMU
              minLength: 1
              maxLength: 35
              pattern: '(^[a-zA-Z0-9\-_\.]{1,35}$)'
            causale:
              type: string
              description: Descrizione della pendenza
              example: 'Sanzione CdS n. abc00000'
              maxLength: 140
            soggettoPagatore:
              $ref: '#/components/schemas/Soggetto'
            importo:
              type: number
              format: double
              description: Importo della pendenza. Deve corrispondere alla somma delle singole voci.
              example: 10.01
              minimum: 0.00
              maximum: 9999999999999999.99
            numeroAvviso:
              type: string
              description: Identificativo univoco versamento, assegnato se pagabile da psp
              example: '123456789012345678'
              pattern: "[0-9]{18}"
            tassonomia:
              type: string
              description: Macro categoria della pendenza secondo la classificazione del creditore
              example: Sanzioni
              maxLength: 35
            tassonomiaAvviso:
              $ref: '#/components/schemas/TassonomiaAvviso'
            dataValidita:
              type: string
              format: date
              description: Data di validita dei dati della pendenza, decorsa la quale la pendenza può subire variazioni.
              example: '2019-12-31'
            dataScadenza:
              type: string
              format: date
              description: Data di scadenza della pendenza, decorsa la quale non è più pagabile.
              example: '2020-12-31'
            annoRiferimento:
              type: integer
              format: int32
              description: Anno di riferimento della pendenza
              example: 2020
              pattern: "[0-9]{4}"
            cartellaPagamento:
              type: string
              description: Identificativo della cartella di pagamento a cui afferisce la pendenza
              example: ABC00000001
              minLength: 1
              maxLength: 35
            datiAllegati:
              type: object
              description: Dati applicativi allegati dal gestionale secondo un formato proprietario.
            direzione:
              type: string
              description: Identificativo della direzione interna all'ente creditore
              example: Direzione ABC
              minLength: 1
              maxLength: 35
            divisione:
              type: string
              description: Identificativo della divisione interna all'ente creditore
              example: Divisione001       
              minLength: 1
              maxLength: 35     
            proprieta:
              $ref: '#/components/schemas/ProprietaPendenza'
            voci:
              type: array
              minItems: 1
              maxItems: 5
              items:
                $ref: '#/components/schemas/NuovaVocePendenza'
            allegati:
              type: array
              items:
                $ref: '#/components/schemas/NuovoAllegatoPendenza'
    NuovaVocePendenza:
      type: object
      allOf:
        - type: object
          required:
          - idVocePendenza
          - importo
          - descrizione
          properties:
            idVocePendenza:
              type: string
              description: Identificativo della voce di pendenza nel gestionale proprietario
              example: abcdef12345_1
              minLength: 1
              maxLength: 35
            importo:
              type: number
              format: double
              description: Importo della voce
              example: 10.01
              minimum: 0.00
              maximum: 9999999999999999.99
            descrizione:
              type: string
              description: descrizione della voce di pagamento
              example: Sanzione CdS n. abc00000
              minLength: 1
              maxLength: 140
            datiAllegati:
              type: object
              description: Dati applicativi allegati dal gestionale secondo un formato proprietario.
            descrizioneCausaleRPT:
              type: string
              description: Testo libero per la causale versamento
              example: Sanzione CdS n. abc00000
              minLength: 1
              maxLength: 140
            contabilita:
                $ref: '#/components/schemas/Contabilita'
            metadata:
                $ref: '#/components/schemas/Metadata'
            idDominio:
              type: string
              description: Identificativo del dominio creditore
              example: '12345678901'
              minLength: 1
              maxLength: 35   
              pattern: '(^([0-9]){11}$)'
        - oneOf:
          - $ref: '#/components/schemas/RiferimentoEntrata'
          - $ref: '#/components/schemas/Entrata'
          - $ref: '#/components/schemas/Bollo'
    NuovoAllegatoPendenza:
      type: object
      required: 
        - nome
        - contenuto
      properties:
        nome:
          type: string
          description: nome del file
          minLength: 1
          maxLength: 255
        tipo:
          type: string
          description: mime type del file
          default: "application/octet-stream"
          minLength: 1
          maxLength: 255
        descrizione:
          type: string
          description: descrizione del file
          minLength: 1
          maxLength: 255
        contenuto: 
          type: string
          format: byte
          description: contenuto del file
    NuovoPagamento:
      type: object
      allOf:
        - type: object
          required:
            - pendenze
          properties:
            pendenze:
              type: array
              description: pendenze o riferimenti alle pendenze oggetto del pagamento
              minItems: 1
              maxItems: 5
              items:
                anyOf:
                  - $ref: '#/components/schemas/RiferimentoPendenza'
                  - $ref: '#/components/schemas/RiferimentoAvviso'
                  - $ref: '#/components/schemas/NuovaPendenza'
                  - $ref: '#/components/schemas/PagamentoSpontaneo'
        - $ref: '#/components/schemas/NuovoPagamentoBase'
    NuovoPagamentoBase:
      type: object
      required:
        - pendenze
      properties:
        urlRitorno:
          type: string
          description: >-
            url di ritorno al portale al termine della sessione di pagamento, il campo e' opzionale, diventa obbligatorio in caso di pagamento con tramite una stazione con versione V2.
          example: >-
            https://www.comune.it/pagamentopagopa/abcd-efgh-ijklm-12345
        contoAddebito:
          $ref: '#/components/schemas/Conto'
        dataEsecuzionePagamento:
          type: string
          format: date
          example: '2018-12-31'
          description: >-
            data in cui si richiede che venga effettuato il pagamento, se diversa dalla data corrente.
        credenzialiPagatore:
          type: string
          description: >-
            Eventuali credenziali richieste dal PSP necessarie per
            completare l'operazione (ad esempio un codice bilaterale
            utilizzabile una sola volta).
        soggettoVersante:
          $ref: '#/components/schemas/Soggetto'
        autenticazioneSoggetto:
          $ref: '#/components/schemas/TipoAutenticazioneSoggetto'
        lingua:
          $ref: '#/components/schemas/LinguaPagamento'
    PagamentoCreato:
      type: object
      required:
        - id
        - location
        - redirect
      properties:
        id:
          type: string
          description: identificativo del pagamento
          example: '12345'
        location:
          type: string
          description: Url del dettaglio del pagamento
          example: /pagamenti/12345
        redirect:
          type: string
          description: url a cui redirigere il navigatore per proseguire nel pagamento.
          example: https://www.comune.it/pagopa/pap/bdd07392-d90d-11e7-9296-cec278b6b50a
        idSession:
          type: string
          description: identificativo della sessione di pagamento per la riconciliazione in al ritorno dal psp.
          example: bdd07392-d90d-11e7-9296-cec278b6b50a
    PagamentoSpontaneo:
      type: object
      required:
        - idDominio
        - idTipoPendenza
      additionalProperties: false
      properties:
        idDominio:
          type: string
          description: Codice fiscale dell'ente creditore
          example: '012345678901'
        idTipoPendenza:
          type: string
          description: >-
            Identificativo della tipologia pendenza
          example: IMU
        dati:
          type: object
          description: Definizione della pendenza              
    ProprietaPendenza:
      type: object
      description: Dati supporto per la gestione del ciclo di vita della pendenza.
      properties:
        linguaSecondaria:
          $ref: '#/components/schemas/LinguaSecondaria'
        descrizioneImporto:
          type: array
          items: 
            $ref: '#/components/schemas/VoceDescrizioneImporto'
        lineaTestoRicevuta1:
          type: string
          description: stringa personalizzata da inserire nella ricevuta
        lineaTestoRicevuta2:
          type: string
          description: stringa personalizzata da inserire nella ricevuta
        linguaSecondariaCausale:
          type: string
          description: >-
              causale della pendenza nella lingua secondaria da inserire nell'avviso
        informativaImportoAvviso:
          type: string
          description: >- 
            se valorizzato, sostituisce il testo standard. Se valorizzato con stringa vuota, l'informativa viene omessa.
          maxLength: 255
        linguaSecondariaInformativaImportoAvviso:
          type: string
          description: >- 
            se valorizzato, sostituisce il testo standard. Se valorizzato con stringa vuota, l'informativa viene omessa.
          maxLength: 255
        dataScandenzaAvviso:
          type: string
          format: date
          description: se valorizzata, sostituisce la data di scadenza standard.
    QuotaContabilita:
      type: object
      required:
        - capitolo
        - annoEsercizio
        - importo
      properties:
        capitolo:
          type: string
          description: Codice del capitolo
          maxLength: 64
        annoEsercizio:
          type: integer
          format: int32
          description: Anno di esercizio
          example: 2020
        importo:
          type: number
          format: double
          description: Importo della voce di contabilita'
          example: 10.01
        accertamento:
          type: string
          description: Codice dell’accertamento
          maxLength: 64        
        proprietaCustom:
          type: object
          description: Dati specifici del gestionale di contabilità
        titolo:
          type: string
          description: Classificazione delle entrate in bilancio
          maxLength: 64
          example: 'titolo'
        tipologia:
          type: string
          description: Classificazione delle entrate in bilancio
          maxLength: 64
          example: 'tipologia'
        categoria:
          type: string
          description: Classificazione delle entrate in bilancio
          maxLength: 64
          example: 'categoria'
        articolo:
          type: string
          description: Classificazione delle entrate in bilancio
          maxLength: 64
          example: 'articolo'
    RiferimentoAvviso:
      type: object
      required:
        - idDominio
        - numeroAvviso
      properties:
        idDominio:
          type: string
          description: Codice fiscale dell'ente creditore
          example: '012345678901'
        numeroAvviso:
          type: string
          description: >-
            Numero avviso della pendenza, assegnato se
            pagabile da psp
          example: '123456789012345678'
          pattern: "[0-9]{18}"
        idDebitore:
          type: string
          description: >-
            Identificativo del soggetto debitore
            della pendenza riferita dall'avviso
          example: 'RSSMRA30A01H501I'
    RiferimentoEntrata:
      description: Definisce i dettagli di incasso tramite riferimento in anagrafica GovPay.
      type: object
      required:
        - codEntrata
      properties:
        codEntrata:
          type: string
          example: SRV-12345
          pattern: '(^[a-zA-Z0-9\-_\.]{1,35}$)'
    RiferimentoPendenza:
      type: object
      required:
        - idA2A
        - idPendenza
      properties:
        idA2A:
          type: string
          description: >-
            Identificativo del gestionale responsabile della
            pendenza
          example: A2A_12345
        idPendenza:
          type: string
          description: >-
            Identificativo della pendenza nel gestionale
            responsabile
          example: abcdef12345
    Soggetto:
      description: dati anagrafici di un versante o pagatore.
      type: object
      required:
        - tipo
        - identificativo
      properties:
        tipo:
          $ref: "#/components/schemas/TipoSoggetto"
        identificativo:
          description: codice fiscale o partita iva del soggetto
          type: string
          example: RSSMRA30A01H501I
          minLength: 2
          maxLength: 16
        anagrafica:
          description: nome e cognome o altra ragione sociale del soggetto
          type: string
          example: Mario Rossi
          minLength: 1
          maxLength: 70
        indirizzo:
          type: string
          example: Piazza della Vittoria
          minLength: 1
          maxLength: 70
        civico:
          type: string
          example: 10/A
          minLength: 1
          maxLength: 16
        cap:
          type: string
          example: '00000'
          minLength: 1
          maxLength: 16
        localita:
          type: string
          example: Roma
          minLength: 1
          maxLength: 35
        provincia:
          type: string
          example: Roma
          minLength: 1
          maxLength: 35
        nazione:
          type: string
          example: IT
          pattern: "[A-Z]{2,2}"
        email:
          type: string
          example: mario.rossi@host.eu
          pattern: "[A-Za-z0-9_]+([\\-\\+\\.'][A-Za-z0-9_]+)*@[A-Za-z0-9_]+([\\-\\.][A-Za-z0-9_]+)*\\.[A-Za-z0-9_]+([\\-\\.][A-Za-z0-9_]+)*"
        cellulare:
          type: string
          example: '+39 000-1234567'
          pattern: "\\+[0-9]{2,2}\\s[0-9]{3,3}\\-[0-9]{7,7}"
    TassonomiaAvviso:
      description: Macro categoria della pendenza Agid
      type: string
      enum:
        - Cartelle esattoriali
        - Diritti e concessioni
        - Imposte e tasse
        - IMU, TASI e altre tasse comunali
        - Ingressi a mostre e musei
        - Multe e sanzioni amministrative
        - Previdenza e infortuni
        - Servizi erogati dal comune
        - Servizi erogati da altri enti
        - Servizi scolastici
        - Tassa automobilistica
        - Ticket e prestazioni sanitarie
        - Trasporti, mobilità e parcheggi
      example:
        Ticket e prestazioni sanitarie
    TipoAutenticazioneSoggetto:
      type: string
      enum:
        - CNS
        - USR
        - OTH
        - N/A
      description: modalita' di autenticazione del soggetto versante
    TipoContabilita:
      description: Tipologia di codifica del capitolo di bilancio
      type: string
      enum:
        - CAPITOLO
        - SPECIALE
        - SIOPE
        - ALTRO
      example: SIOPE
    TipoSoggetto:
      description: >-
        tipologia di soggetto, se persona fisica (F) o giuridica
        (G)
      type: string
      enum:
        - G
        - F
      example: F
    VoceDescrizioneImporto:
      type: object
      properties:
        voce: 
          type: string
          description: voce importo
          example: canone annuo
        importo: 
          type: number
          format: double
          description: importo
          example: 10.01